# Generated by Django 5.1.3 on 2024-12-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sources_classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'PS Data Entry and Monitoring'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_budget', to='core.account_code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='account_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='an_budget', to='core.account_name'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rf_budget', to='core.reference'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_budget', to='core.workgroup'),
        ),
        migrations.CreateModel(
            name='funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sl_code', models.CharField(blank=True, max_length=255, null=True)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_funds', to='core.account_code')),
                ('account_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='an_funds', to='core.account_name')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rf_funds', to='core.reference')),
                ('workgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_funds', to='core.workgroup')),
                ('sources_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sources_classification')),
            ],
            options={
                'verbose_name': 'Sources of Funds Data Entry and Monitoring',
            },
        ),
    ]
