# Generated by Django 5.1.3 on 2024-12-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_choose_sl_code_and_name_alter_funds_sl_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='mooe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_mooe', to='core.account_code')),
                ('account_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='an_mooe', to='core.account_name')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rf_mooe', to='core.reference')),
                ('sl_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_mooe', to='core.sl_code_and_name')),
                ('sources_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sources_classification')),
                ('workgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_mooe', to='core.workgroup')),
            ],
            options={
                'verbose_name': 'MOOE Data Entry and Monitoring',
            },
        ),
    ]
