# Generated by Django 5.1.3 on 2024-12-06 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mooe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mooe',
            name='received_from',
        ),
        migrations.RemoveField(
            model_name='mooe',
            name='sl_code',
        ),
        migrations.RemoveField(
            model_name='mooe',
            name='sources_classification',
        ),
        migrations.AddField(
            model_name='mooe',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.budget_category'),
        ),
        migrations.AddField(
            model_name='mooe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mooe',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payee'),
        ),
        migrations.AlterField(
            model_name='mooe',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
