# Generated by Django 5.1.3 on 2024-12-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_budget_category_workgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_category',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='core.workgroup'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
