# Generated by Django 5.1.3 on 2024-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_budget_category_workgroup_alter_workgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
