# Generated by Django 5.1.3 on 2024-12-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_workgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget_category',
            name='workgroup',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='workgroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_budget', to='core.workgroup'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_funds', to='core.workgroup'),
        ),
        migrations.AlterField(
            model_name='mooe',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wg_mooe', to='core.workgroup'),
        ),
    ]
