# Generated by Django 5.1.3 on 2024-12-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_budget_category_workgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='workgroup',
        ),
        migrations.AddField(
            model_name='budget_category',
            name='workgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='core.workgroup'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='name',
            field=models.CharField(default='Default Workgroup', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='core.workgroup'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds', to='core.workgroup'),
        ),
        migrations.AlterField(
            model_name='mooe',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mooes', to='core.workgroup'),
        ),
    ]
